import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const PulauSumatera = forwardRef(({ onClick, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/sumatera.glb");

  const handleClick = (e) => {
    console.log("Island1 clicked");
    if (onClick) onClick(e);
  };

  return (
    <group ref={ref} {...props} dispose={null} onClick={handleClick}>
      <group rotation={[0.062, -0.394, -0.185]} scale={5.254}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7"].geometry
          }
          material={materials["tripo_mat_acc096fb-f722-42cd-81e4-ab4df5027bf7"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_1"].geometry
          }
          material={materials["M_Island_2.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_2"].geometry
          }
          material={materials["M_Island_2.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_3"].geometry
          }
          material={materials["M_Flowers.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_4"].geometry
          }
          material={materials.M_Flowers}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_5"].geometry
          }
          material={materials.M_Island_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_6"].geometry
          }
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_7"].geometry
          }
          material={materials["Icosphere.010__0.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_8"].geometry
          }
          material={materials["Icosphere.010__0"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_9"].geometry
          }
          material={materials["Icosphere.010__0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_10"].geometry
          }
          material={materials["Icosphere.010__0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_11"].geometry
          }
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_12"].geometry
          }
          material={materials["M_Mushrooms.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_13"].geometry
          }
          material={materials.M_Mushrooms}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_14"].geometry
          }
          material={materials["M_Island_2.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_15"].geometry
          }
          material={materials.M_Island_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_16"].geometry
          }
          material={materials["M_Island_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_17"].geometry
          }
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_18"].geometry
          }
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_19"].geometry
          }
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_20"].geometry
          }
          material={materials.atap_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_21"].geometry
          }
          material={materials["papan__rumah_2_no_1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["tripo_mesh_acc096fb-f722-42cd-81e4-ab4df5027bf7_22"].geometry
          }
          material={materials.papan__rumah_2_no_1}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/models/sumatera.glb");
